version: '3.3'
services:
  # hivemq:
  #   image: hivemq/hivemq4
  #   ports:
  #    - "8080:8080"
  #    - "1883:1883"
  # db:
  #   image: quay.io/influxdb/influxdb:v2.0.4
  #   environment: 
  #     - INFLUXDB_ADMIN_USER_PASSWORD=adminadmin
  #     - INFLUXDB_USER_BUCKET=soa
  #     - INFLUXDB_USER_ORGANIZATION=soa
  #   volumes:
  #       - influxdbData:/.influxdbData
  #   ports:
  #     - "8086:8086"
  #   depends_on: 
  #     - hivemq
  coolant:
    image: coolantdev
    build:
        context: ./CoolingDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
         - redis
    volumes:
         - C:\Users\lukac\source\repos\SOA:/SOA
  data:
    image: data
    build:
        context: ./DataMicroservice
        dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on: 
      - redis
  redis:
    image: redis:latest
    command: bash -c "redis-server --appendonly yes"
    ports:
      - 6379:6379
    volumes:
      - redisVol:/data:rw

  # volumes:
  #   redis-vol:
    # depends_on:
    #     - db
  stator:
    image: statordev
    build:
        context: ./StatorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
         - redis
    volumes:
         - C:\Users\lukac\source\repos\SOA:/SOA
  motor:
    image: motordev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
         - redis
    volumes:
         - C:\Users\lukac\source\repos\SOA:/SOA
#   # gateway: 
#     # image: gateway
#     # build:
#         # context: ./GatewayMicroservice
#         # dockerfile: Dockerfile
#     # ports:
#       # - "5008:80"
volumes:
    redisVol:
