version: '3.3'
services:
  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
     - "8080:8080"
     - "1883:1883"
  coolant:
    image: coolantdev
    build:
        context: ./CoolingDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
         - mongodbData
    volumes:
         - C:\Users\455g7\Desktop\SOA_Gorana:/SOA
  stator:
    image: statordev
    build:
        context: ./StatorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - C:\Users\455g7\Desktop\SOA_Gorana:/SOA
    depends_on: 
      - mongodbData
  motor:
    image: motordev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
          - mongodbData
    volumes:
     - C:\Users\455g7\Desktop\SOA_Gorana:/SOA
  command:
    image: commanddev
    build:
        context: ./CommandMIcroService
        dockerfile: Dockerfile
    ports:
      - "7000:80"
    depends_on:
      - hivemq
  analytics:
    image: analyticsdev
    build:
        context: ./AnalyticsMicroservice
        dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - hivemq
    volumes: 
      - mongodbAnalytics:/data   
  data:
    image: data
    build:
        context: ./DataMicroservice
        dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on: 
      - mongodbData
    volumes:
      - mongodbData:/data 
  mongodbData:
    image : mongo
    container_name: mongodbData
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodbData:/data   
    depends_on: 
       - hivemq  
  mongodbAnalytics:
    image : mongo
    container_name: mongodbAnalytics
    ports:
      - "27018:27017"
    restart: unless-stopped
    volumes:
      - mongodbAnalytics:/data   
    depends_on:  
        - hivemq
  gateway:
    image: gatewaydev
    build:
      context: ./GatewayMicroservice
      dockerfile: Dockerfile
    ports:
      - "7005:80"
    expose:
      - "80"
    depends_on: 
      - command
volumes:
    mongodbData:
    mongodbAnalytics:
