version: '3.3'
services:
  hivemq:
    image: hivemq/hivemq4
    container_name: hivemq
    ports:
     - "8080:8080"
     - "1883:1883"
  coolant:
    image: coolantdev
    build:
        context: ./CoolingDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
         - mongodb
    volumes:
<<<<<<< HEAD
         - C:\Users\Zeljko\Desktop\SOA:/SOA
  stator:
    image: statordev
    build:
        context: ./StatorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - C:\Users\Zeljko\Desktop\SOA:/app/data/
    depends_on: 
      - mongodb
  motor:
    image: motordev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
          - mongodb
  command:
    image: commanddev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "7000:80"
    depends_on:
      - mongodb
=======
         - C:\Users\lukac\source\repos\SOA:/SOA
>>>>>>> a0257b99e7c81c4f4783b3fb90aec616a8398df2
  data:
    image: data
    build:
        context: ./DataMicroservice
        dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on: 
      - mongodb
    volumes:
      - mongoDb:/data 
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
<<<<<<< HEAD
      - mongoDb:/data   
    depends_on: 
       - hivemq  
  # gateway:
  #   image: gatewaydev
  #   build:
  #     context: ./GatewayMicroservice
  #     dockerfile: Dockerfile
  #     ports:
  #       - 7005:80
volumes:
    mongoDb:
=======
      - redisVol:/data:rw

  # volumes:
  #   redis-vol:
    # depends_on:
    #     - db
  stator:
    image: statordev
    build:
        context: ./StatorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
         - redis
    volumes:
         - C:\Users\lukac\source\repos\SOA:/SOA
  motor:
    image: motordev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
         - redis
    volumes:
         - C:\Users\lukac\source\repos\SOA:/SOA
#   # gateway: 
#     # image: gateway
#     # build:
#         # context: ./GatewayMicroservice
#         # dockerfile: Dockerfile
#     # ports:
#       # - "5008:80"
volumes:
    redisVol:
>>>>>>> a0257b99e7c81c4f4783b3fb90aec616a8398df2
