version: '3.3'
services:
  db:
    image: quay.io/influxdb/influxdb:v2.0.4
    environment: 
      - INFLUXDB_ADMIN_USER_PASSWORD=adminadmin
      - INFLUXDB_USER_BUCKET=soa
      - INFLUXDB_USER_ORGANIZATION=soa
    volumes:
        - influxdbData:/.influxdbData
    ports:
      - "8086:8086"
  coolant:
    image: coolantdev
    build:
        context: ./CoolingDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
        - db
  data:
    image: data
    build:
        context: ./DataMicroservice
        dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
        - db
  stator:
    image: statordev
    build:
        context: ./StatorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
        - db
  motor:
    image: motordev
    build:
        context: ./MotorDeviceMicroservice
        dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
        - db
  # gateway: 
    # image: gateway
    # build:
        # context: ./GatewayMicroservice
        # dockerfile: Dockerfile
    # ports:
      # - "5008:80"
volumes:
  influxdbData: